from __future__ import annotations

import re
import unicodedata
from collections.abc import Iterable
from typing import Any

from miner.agent_v1.artifact_models import Artifact, SourceRef

from .models import AgentV1ValidationFinding


VALID_ROLES = {"input", "result", "method", "interpretation", "metadata"}


def run_grounding_checks(artifact: Artifact | None, source_payload: dict[str, Any] | None) -> list[AgentV1ValidationFinding]:
    if artifact is None:
        return []
    if not source_payload:
        return _number_findings(
            [
                AgentV1ValidationFinding(
                    pass_name="grounding",
                    dimension="source_payload",
                    severity="critical",
                    target_type="source_payload",
                    message="No source_payload.json was provided; source grounding cannot be verified.",
                    suggestion="Provide the source_payload.json generated by miner.agent_v1.",
                    metadata={"code": "missing_source_payload"},
                )
            ]
        )
    span_text_by_id = {
        str(span.get("span_id")): str(span.get("text") or "")
        for span in source_payload.get("spans", []) or []
        if span.get("span_id")
    }
    findings: list[AgentV1ValidationFinding] = []

    for claim in artifact.logic.claims:
        source_refs = list(claim.sources)
        if not source_refs and not claim.evidence_ids:
            findings.append(_finding("critical", "claim_grounding", "Claim has no sources or evidence IDs.", "claim", claim.claim_id, code="no_source_refs"))
        findings.extend(_check_refs(source_refs, span_text_by_id, "claim", claim.claim_id))
        findings.extend(_check_numbers(claim.statement + " " + claim.conditions, source_refs, span_text_by_id, "claim", claim.claim_id))

    for evidence in artifact.evidence.records:
        if not evidence.source_refs:
            findings.append(
                _finding(
                    "critical",
                    "evidence_grounding",
                    "Evidence record has no source refs.",
                    "evidence",
                    evidence.evidence_id,
                    code="no_source_refs",
                )
            )
        findings.extend(_check_refs(evidence.source_refs, span_text_by_id, "evidence", evidence.evidence_id))
        findings.extend(_check_numbers(evidence.summary, evidence.source_refs, span_text_by_id, "evidence", evidence.evidence_id))

    for experiment in artifact.logic.experiments:
        findings.extend(_check_refs(experiment.source_refs, span_text_by_id, "experiment", experiment.experiment_id))
        findings.extend(
            _check_numbers(
                " ".join([experiment.setup, experiment.procedure, experiment.expected_outcome]),
                experiment.source_refs,
                span_text_by_id,
                "experiment",
                experiment.experiment_id,
                severity="minor",
            )
        )

    return _number_findings(findings)


def _check_refs(
    source_refs: Iterable[SourceRef],
    span_text_by_id: dict[str, str],
    target_type: str,
    target_id: str,
) -> list[AgentV1ValidationFinding]:
    findings: list[AgentV1ValidationFinding] = []
    for ref in source_refs:
        if ref.role not in VALID_ROLES:
            findings.append(_finding("major", "source_ref_role", f"Invalid source ref role: {ref.role}.", target_type, target_id, code="invalid_source_role"))
        if not ref.span_ids and ref.source_type == "span":
            findings.append(_finding("major", "source_ref_span", "Span source ref has no span IDs.", target_type, target_id, code="missing_source_span"))
        for span_id in ref.span_ids:
            if span_id not in span_text_by_id:
                findings.append(
                    _finding(
                        "critical",
                        "source_ref_span",
                        f"Source ref points to missing span ID: {span_id}.",
                        target_type,
                        target_id,
                        code="missing_source_span",
                        ref_id=ref.source_id,
                        span_id=span_id,
                    )
                )
        if ref.quote:
            joined = " ".join(span_text_by_id.get(span_id, "") for span_id in ref.span_ids)
            if joined and not _contains_normalized(joined, ref.quote):
                findings.append(
                    _finding(
                        "critical",
                        "source_quote_grounding",
                        "Source quote does not appear in the referenced source span text.",
                        target_type,
                        target_id,
                        evidence_span=ref.quote,
                        code="quote_not_in_source",
                        ref_id=ref.source_id,
                    )
                )
    return findings


def _check_numbers(
    text: str,
    source_refs: Iterable[SourceRef],
    span_text_by_id: dict[str, str],
    target_type: str,
    target_id: str,
    *,
    severity: str = "major",
) -> list[AgentV1ValidationFinding]:
    numbers = _numbers(text)
    if not numbers:
        return []
    source_text = " ".join(
        " ".join([ref.quote or "", *[span_text_by_id.get(span_id, "") for span_id in ref.span_ids]]) for ref in source_refs
    )
    normalized_source = _normalize(source_text)
    normalized_source_digits = normalized_source.replace(",", "").replace(" ", "")
    findings = []
    for number in numbers:
        normalized_number = _normalize_number(number)
        if normalized_number not in normalized_source and normalized_number not in normalized_source_digits:
            findings.append(
                _finding(
                    severity,
                    "numeric_grounding",
                    f"Number `{number}` is not present in connected source refs or source spans.",
                    target_type,
                    target_id,
                    evidence_span=number,
                    code="number_not_grounded",
                )
            )
    return findings


def _numbers(text: str) -> set[str]:
    return set(re.findall(r"(?<![A-Za-z])(?:\d+(?:,\d{3})*(?:\.\d+)?|\.\d+)(?:\s?%|e[+-]?\d+)?", text, flags=re.IGNORECASE))


def _normalize_number(number: str) -> str:
    return _normalize(number).replace(",", "").replace(" ", "")


def _contains_normalized(haystack: str, needle: str) -> bool:
    normalized_haystack = _normalize(haystack)
    normalized_needle = _normalize(needle)
    if normalized_needle in normalized_haystack:
        return True
    return _has_ordered_token_support(normalized_haystack, normalized_needle)


def _normalize(text: str) -> str:
    text = unicodedata.normalize("NFKC", text)
    text = text.casefold()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _has_ordered_token_support(haystack: str, needle: str) -> bool:
    needle_tokens = _quote_tokens(needle)
    if len(needle_tokens) < 6:
        return False
    haystack_tokens = _quote_tokens(haystack)
    if not haystack_tokens:
        return False
    matched = _best_compact_ordered_match_count(haystack_tokens, needle_tokens)
    coverage = matched / len(needle_tokens)
    return coverage >= 0.75


def _quote_tokens(text: str) -> list[str]:
    tokens = re.findall(r"[a-z0-9]+", _normalize(text))
    return [token for token in tokens if len(token) > 1 or token.isdigit()]


def _ordered_token_match_count(haystack_tokens: list[str], needle_tokens: list[str]) -> int:
    cursor = 0
    matched = 0
    for token in needle_tokens:
        try:
            index = haystack_tokens.index(token, cursor)
        except ValueError:
            continue
        matched += 1
        cursor = index + 1
    return matched


def _best_compact_ordered_match_count(haystack_tokens: list[str], needle_tokens: list[str]) -> int:
    window_size = max(len(needle_tokens) * 3, len(needle_tokens) + 20)
    if len(haystack_tokens) <= window_size:
        return _ordered_token_match_count(haystack_tokens, needle_tokens)
    best = 0
    for start in range(0, len(haystack_tokens) - window_size + 1):
        matched = _ordered_token_match_count(haystack_tokens[start : start + window_size], needle_tokens)
        if matched > best:
            best = matched
            if best == len(needle_tokens):
                break
    return best


def _finding(
    severity: str,
    dimension: str,
    message: str,
    target_type: str,
    target_id: str,
    *,
    evidence_span: str | None = None,
    code: str,
    **metadata,
) -> AgentV1ValidationFinding:
    return AgentV1ValidationFinding(
        pass_name="grounding",
        dimension=dimension,
        severity=severity,  # type: ignore[arg-type]
        target_type=target_type,
        target_id=target_id,
        message=message,
        evidence_span=evidence_span,
        suggestion=_suggestion_for_code(code),
        metadata={"code": code, **metadata},
    )


def _suggestion_for_code(code: str) -> str:
    return {
        "missing_source_payload": "Pass the miner run source_payload.json into validator.agent_v1.",
        "invalid_source_role": "Use one of the allowed source roles.",
        "missing_source_span": "Point the source ref to a span ID present in source_payload.json.",
        "quote_not_in_source": "Replace the quote with an exact excerpt from the referenced source span.",
        "number_not_grounded": "Ground each load-bearing number in a connected source quote or span.",
        "no_source_refs": "Add source refs grounded in the provided source payload.",
    }.get(code, "Repair the source grounding.")


def _number_findings(findings: list[AgentV1ValidationFinding]) -> list[AgentV1ValidationFinding]:
    for index, finding in enumerate(findings, start=1):
        finding.finding_id = f"G{index:03d}"
    return findings
